# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxxBctMjqJezFSmHmfO6Pa9osCGLteK2
"""

import pandas as pd
import os

df = pd.DataFrame({
    "name": ["Alice", "Bob"],
    "score": [85, 92]
})

# Create the directory if it doesn't exist
os.makedirs('/data', exist_ok=True)

df.to_csv("/data/output.csv", index=False)
print("Data processed -> /data/output.csv")